// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ekbole/pruner.proto

package ekbole

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Provisioned Kubernetes manifest.
type PruneStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manifest      []byte                 `protobuf:"bytes,1,opt,name=manifest,proto3" json:"manifest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PruneStreamRequest) Reset() {
	*x = PruneStreamRequest{}
	mi := &file_ekbole_pruner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PruneStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PruneStreamRequest) ProtoMessage() {}

func (x *PruneStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ekbole_pruner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PruneStreamRequest.ProtoReflect.Descriptor instead.
func (*PruneStreamRequest) Descriptor() ([]byte, []int) {
	return file_ekbole_pruner_proto_rawDescGZIP(), []int{0}
}

func (x *PruneStreamRequest) GetManifest() []byte {
	if x != nil {
		return x.Manifest
	}
	return nil
}

// Pruned Kubernetes resource.
type PruneStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manifest      []byte                 `protobuf:"bytes,1,opt,name=manifest,proto3" json:"manifest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PruneStreamResponse) Reset() {
	*x = PruneStreamResponse{}
	mi := &file_ekbole_pruner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PruneStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PruneStreamResponse) ProtoMessage() {}

func (x *PruneStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ekbole_pruner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PruneStreamResponse.ProtoReflect.Descriptor instead.
func (*PruneStreamResponse) Descriptor() ([]byte, []int) {
	return file_ekbole_pruner_proto_rawDescGZIP(), []int{1}
}

func (x *PruneStreamResponse) GetManifest() []byte {
	if x != nil {
		return x.Manifest
	}
	return nil
}

// Provisioned Kubernetes manifest.
type PruneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manifest      []byte                 `protobuf:"bytes,1,opt,name=manifest,proto3" json:"manifest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PruneRequest) Reset() {
	*x = PruneRequest{}
	mi := &file_ekbole_pruner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PruneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PruneRequest) ProtoMessage() {}

func (x *PruneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ekbole_pruner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PruneRequest.ProtoReflect.Descriptor instead.
func (*PruneRequest) Descriptor() ([]byte, []int) {
	return file_ekbole_pruner_proto_rawDescGZIP(), []int{2}
}

func (x *PruneRequest) GetManifest() []byte {
	if x != nil {
		return x.Manifest
	}
	return nil
}

// Pruned Kubernetes resource.
type PruneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PruneResponse) Reset() {
	*x = PruneResponse{}
	mi := &file_ekbole_pruner_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PruneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PruneResponse) ProtoMessage() {}

func (x *PruneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ekbole_pruner_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PruneResponse.ProtoReflect.Descriptor instead.
func (*PruneResponse) Descriptor() ([]byte, []int) {
	return file_ekbole_pruner_proto_rawDescGZIP(), []int{3}
}

var File_ekbole_pruner_proto protoreflect.FileDescriptor

const file_ekbole_pruner_proto_rawDesc = "" +
	"\n" +
	"\x13ekbole/pruner.proto\x12\x06ekbole\"0\n" +
	"\x12PruneStreamRequest\x12\x1a\n" +
	"\bmanifest\x18\x01 \x01(\fR\bmanifest\"1\n" +
	"\x13PruneStreamResponse\x12\x1a\n" +
	"\bmanifest\x18\x01 \x01(\fR\bmanifest\"*\n" +
	"\fPruneRequest\x12\x1a\n" +
	"\bmanifest\x18\x01 \x01(\fR\bmanifest\"\x0f\n" +
	"\rPruneResponse2\x93\x01\n" +
	"\rPrunerService\x12J\n" +
	"\vPruneStream\x12\x1a.ekbole.PruneStreamRequest\x1a\x1b.ekbole.PruneStreamResponse(\x010\x01\x126\n" +
	"\x05Prune\x12\x14.ekbole.PruneRequest\x1a\x15.ekbole.PruneResponse(\x01B\x1eZ\x1cgithub.com/katastroma/ekboleb\x06proto3"

var (
	file_ekbole_pruner_proto_rawDescOnce sync.Once
	file_ekbole_pruner_proto_rawDescData []byte
)

func file_ekbole_pruner_proto_rawDescGZIP() []byte {
	file_ekbole_pruner_proto_rawDescOnce.Do(func() {
		file_ekbole_pruner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ekbole_pruner_proto_rawDesc), len(file_ekbole_pruner_proto_rawDesc)))
	})
	return file_ekbole_pruner_proto_rawDescData
}

var file_ekbole_pruner_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_ekbole_pruner_proto_goTypes = []any{
	(*PruneStreamRequest)(nil),  // 0: ekbole.PruneStreamRequest
	(*PruneStreamResponse)(nil), // 1: ekbole.PruneStreamResponse
	(*PruneRequest)(nil),        // 2: ekbole.PruneRequest
	(*PruneResponse)(nil),       // 3: ekbole.PruneResponse
}
var file_ekbole_pruner_proto_depIdxs = []int32{
	0, // 0: ekbole.PrunerService.PruneStream:input_type -> ekbole.PruneStreamRequest
	2, // 1: ekbole.PrunerService.Prune:input_type -> ekbole.PruneRequest
	1, // 2: ekbole.PrunerService.PruneStream:output_type -> ekbole.PruneStreamResponse
	3, // 3: ekbole.PrunerService.Prune:output_type -> ekbole.PruneResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ekbole_pruner_proto_init() }
func file_ekbole_pruner_proto_init() {
	if File_ekbole_pruner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ekbole_pruner_proto_rawDesc), len(file_ekbole_pruner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ekbole_pruner_proto_goTypes,
		DependencyIndexes: file_ekbole_pruner_proto_depIdxs,
		MessageInfos:      file_ekbole_pruner_proto_msgTypes,
	}.Build()
	File_ekbole_pruner_proto = out.File
	file_ekbole_pruner_proto_goTypes = nil
	file_ekbole_pruner_proto_depIdxs = nil
}
