// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: ekbole/pruner.proto

package ekbole

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PrunerService_PruneStream_FullMethodName = "/ekbole.PrunerService/PruneStream"
	PrunerService_Prune_FullMethodName       = "/ekbole.PrunerService/Prune"
)

// PrunerServiceClient is the client API for PrunerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PrunerService removes cluster resources no longer in the manifest set.
type PrunerServiceClient interface {
	PruneStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PruneStreamRequest, PruneStreamResponse], error)
	Prune(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PruneRequest, PruneResponse], error)
}

type prunerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPrunerServiceClient(cc grpc.ClientConnInterface) PrunerServiceClient {
	return &prunerServiceClient{cc}
}

func (c *prunerServiceClient) PruneStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PruneStreamRequest, PruneStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PrunerService_ServiceDesc.Streams[0], PrunerService_PruneStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PruneStreamRequest, PruneStreamResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PrunerService_PruneStreamClient = grpc.BidiStreamingClient[PruneStreamRequest, PruneStreamResponse]

func (c *prunerServiceClient) Prune(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PruneRequest, PruneResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PrunerService_ServiceDesc.Streams[1], PrunerService_Prune_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PruneRequest, PruneResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PrunerService_PruneClient = grpc.ClientStreamingClient[PruneRequest, PruneResponse]

// PrunerServiceServer is the server API for PrunerService service.
// All implementations must embed UnimplementedPrunerServiceServer
// for forward compatibility.
//
// PrunerService removes cluster resources no longer in the manifest set.
type PrunerServiceServer interface {
	PruneStream(grpc.BidiStreamingServer[PruneStreamRequest, PruneStreamResponse]) error
	Prune(grpc.ClientStreamingServer[PruneRequest, PruneResponse]) error
	mustEmbedUnimplementedPrunerServiceServer()
}

// UnimplementedPrunerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPrunerServiceServer struct{}

func (UnimplementedPrunerServiceServer) PruneStream(grpc.BidiStreamingServer[PruneStreamRequest, PruneStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method PruneStream not implemented")
}
func (UnimplementedPrunerServiceServer) Prune(grpc.ClientStreamingServer[PruneRequest, PruneResponse]) error {
	return status.Error(codes.Unimplemented, "method Prune not implemented")
}
func (UnimplementedPrunerServiceServer) mustEmbedUnimplementedPrunerServiceServer() {}
func (UnimplementedPrunerServiceServer) testEmbeddedByValue()                       {}

// UnsafePrunerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PrunerServiceServer will
// result in compilation errors.
type UnsafePrunerServiceServer interface {
	mustEmbedUnimplementedPrunerServiceServer()
}

func RegisterPrunerServiceServer(s grpc.ServiceRegistrar, srv PrunerServiceServer) {
	// If the following call panics, it indicates UnimplementedPrunerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PrunerService_ServiceDesc, srv)
}

func _PrunerService_PruneStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PrunerServiceServer).PruneStream(&grpc.GenericServerStream[PruneStreamRequest, PruneStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PrunerService_PruneStreamServer = grpc.BidiStreamingServer[PruneStreamRequest, PruneStreamResponse]

func _PrunerService_Prune_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PrunerServiceServer).Prune(&grpc.GenericServerStream[PruneRequest, PruneResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PrunerService_PruneServer = grpc.ClientStreamingServer[PruneRequest, PruneResponse]

// PrunerService_ServiceDesc is the grpc.ServiceDesc for PrunerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PrunerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ekbole.PrunerService",
	HandlerType: (*PrunerServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PruneStream",
			Handler:       _PrunerService_PruneStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Prune",
			Handler:       _PrunerService_Prune_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "ekbole/pruner.proto",
}
