syntax = "proto3";

package ekbole;

option go_package = "github.com/katastroma/ekbole";

// PrunerService removes cluster resources no longer in the manifest set.
service PrunerService {
  rpc PruneStream(stream PruneStreamRequest) returns (stream PruneStreamResponse);
  rpc Prune(stream PruneRequest) returns (PruneResponse);
}

// Provisioned Kubernetes manifest.
message PruneStreamRequest {
  bytes manifest = 1;
}

// Pruned Kubernetes resource.
message PruneStreamResponse {
  bytes manifest = 1;
}

// Provisioned Kubernetes manifest.
message PruneRequest {
  bytes manifest = 1;
}

// Pruned Kubernetes resource.
message PruneResponse {}
